name: journey_app # 项目的包名
description: "Journey app"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  card_swiper: ^3.0.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18+3
  provider: ^6.1.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# 通过命令 flutter pub run flutter_launcher_icons:main ，使用 images/icon1024.png 生成一系列图片
flutter_icons:
  image_path: "images/icon1024.png"
  android: true
  ios: true
